## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [3]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape) # se pide (4,4)
# Uso de bucles for para crear una lista en python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [14]:
lista = []

for i in range(4):
    
    fila = [random.randint(1, 100) for i in range(4)]
    
    lista.append(fila)
    
    
matriz = np.array(lista)
    
print(matriz)
print(matriz.shape)


[[34 90 98 22]
 [ 1 61  1 54]
 [50  9 10  8]
 [28  3 83 30]]
(4, 4)


### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [5]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape) # se pide (m, n)
# Uso de bucles for para crear una lista en python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [18]:
lista = []

def generar_matriz(m, n):
    
    for i in range(m):
        
        fila = [random.randint(1, 100) for i in range(n)]
        
        lista.append(fila)  
    
    return np.array(lista)
        
matriz = generar_matriz(5, 3)

print(matriz)


[[95 89  9]
 [69 90 26]
 [73 48 61]
 [99  1 87]
 [23 84  3]]


In [6]:
##############################################################################################################################