## Ejercicios - NumPy 1

In [1]:
import numpy as np

In [2]:
# Versión
print(f"numpy=={np.__version__}")

numpy==1.26.4


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [3]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)

np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)

np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
array_pares = np.array([i for i in range(2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [6]:
array_pares.ndim

1

In [7]:
# numero de elementos en total
array_pares.size

10

In [8]:
# numero de elementos en cada dimension
array_pares.shape

(10,)

In [9]:
array_pares.dtype

dtype('int64')

In [10]:
array = np.array([10, 10, 20, 20, 30, 30])
array

array([10, 10, 20, 20, 30, 30])

In [11]:
array_acumulado = np.cumsum(array)
array_acumulado

array([ 10,  20,  40,  60,  90, 120])

In [12]:
np.diff(array_acumulado)

array([10, 20, 20, 30, 30])

In [13]:
# agregar el primero manualmente ya que no tiene ninguno delante para obtener el diff
original = np.insert(np.diff(array_acumulado), 0, array_acumulado[0])
original

array([10, 10, 20, 20, 30, 30])

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [14]:
pares = np.array([i for i in range(2, 11, 2)])
pares

array([ 2,  4,  6,  8, 10])

In [15]:
impares = np.array([i for i in range(1, 11, 2)])
impares

array([1, 3, 5, 7, 9])

In [16]:
# concatenate y reshape. Por defecto es axis=0. Como es vector de 1 dimensión, axis 1 da error, no hay dos dimensiones
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [17]:
matriz_5x2 = numbers.reshape(5, 2)
matriz_5x2


array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [18]:
matriz_5x2.shape

(5, 2)

In [19]:
# lo aplana de 2 dimensiones a una dimensión:
matriz_5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [20]:
np.ravel(matriz_5x2)

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [21]:
# esto interesa si los datos son pareados, y están relacionados,
# Por ejemplo si queremos combinar elemento a elemento de un array city_consumption con road_consumption
np.column_stack((pares, impares))

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [22]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [23]:
indices = np.where(pares > 5) # devuelve los indices de los elementos que cumplen con la condiciones/es
pares[indices] # usamos los indices como filtros

array([ 6,  8, 10])

In [24]:
# en pandas
# filtro = df['price'] > 20
# df[filtro]

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [25]:
matriz_5x2.dtype

dtype('int64')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

In [32]:
# Crear una matriz de ceros de dimensión (4, 4)
matriz = np.zeros((4, 4))

# Reemplazar los elementos de la diagonal principal por 5
np.fill_diagonal(matriz, 5)

print(matriz)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

In [34]:
linespace = np.linspace(start= -5, stop= 5, num= 10)

linespace

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

In [35]:
# Crear una matriz vacía de tamaño (3, 6) con elementos flotantes
matriz_vacia = np.empty((3, 6), dtype=float)

print(matriz_vacia)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

In [36]:

# Función para generar números primos
def generar_primos(n):

    primos = []
    num = 2
    while len(primos) < n:
        es_primo = all(num % p != 0 for p in primos)
        if es_primo:
            primos.append(num)
        num += 1
    return primos

# Crear una matriz vacía de tamaño (3, 6)
matriz_vacia = np.empty((3, 6), dtype=float)

# Generar suficientes números primos para llenar la matriz
n_elementos = matriz_vacia.size  # Número total de elementos en la matriz
primos = generar_primos(n_elementos)

# Llenar la matriz con los números primos
matriz_vacia[:] = np.array(primos).reshape(matriz_vacia.shape)

print("Matriz llena con números primos:")
print(matriz_vacia)

Matriz llena con números primos:
[[ 2.  3.  5.  7. 11. 13.]
 [17. 19. 23. 29. 31. 37.]
 [41. 43. 47. 53. 59. 61.]]


### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

In [37]:
# Crear la matriz inicial
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Reemplazar los números azules con 99 usando slicing
matriz[0, 2] = 99  # Elemento (0, 2) -> 3
matriz[1, 1] = 99  # Elemento (1, 1) -> 6
matriz[1, 3] = 99  # Elemento (1, 3) -> 8
matriz[2, 0] = 99  # Elemento (2, 0) -> 9
matriz[3, 2] = 99  # Elemento (3, 2) -> 15

print("Matriz después de reemplazar los números azules por 99:")
print(matriz)

Matriz después de reemplazar los números azules por 99:
[[ 1  2 99  4]
 [ 5 99  7 99]
 [99 10 11 12]
 [13 14 99 16]]


### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

In [38]:

# Obtener la primera y tercera fila
resultado = matriz[[0, 2], :]

print("Primera y tercera fila de la matriz:")
print(resultado)

Primera y tercera fila de la matriz:
[[ 1  2 99  4]
 [99 10 11 12]]


### Ejercico 11:
- Obten la tercera columna de la matriz.

In [39]:
# Obtener la tercera columna
tercera_columna = matriz[:, 2]

print("Tercera columna de la matriz:")
print(tercera_columna)

Tercera columna de la matriz:
[99  7 11 99]


### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

In [42]:
segunda_tercera_columna = matriz[: , 1:3]

print("Segunda y tercera columna de la matriz:")
print(segunda_tercera_columna)

Segunda y tercera columna de la matriz:
[[ 2 99]
 [99  7]
 [10 11]
 [14 99]]


### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

In [43]:
# Obtener la submatriz con los números del centro
submatriz_centro = matriz[1:3, 1:3]  # Filas 1 a 2 y columnas 1 a 2

print("Submatriz con los 4 números del centro:")
print(submatriz_centro)

Submatriz con los 4 números del centro:
[[99  7]
 [10 11]]


### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

In [46]:
vector = submatriz_centro.flatten()

print("Vector obtenido con np.flatten():")
print(vector)

Vector obtenido con np.flatten():
[99  7 10 11]


### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

In [48]:
vector.reshape(1, 4)

array([[99,  7, 10, 11]])

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [27]:
import numpy as np

A = np.random.randn(4, 4)
A


array([[-1.93181852, -0.24991737, -2.85593244, -0.48040933],
       [ 1.19563683, -0.56318729, -1.11334208, -0.21519366],
       [ 0.242841  , -0.95549184, -1.25239073,  0.4094317 ],
       [-1.28380913, -0.47069011, -1.59423148,  0.43463326]])

In [28]:
B = np.random.randn(4, 4)
B

array([[-0.82246258,  1.48670351,  0.39458751, -1.07019225],
       [-0.780698  ,  0.98568704, -0.29036583,  1.20002403],
       [ 0.18748337,  1.01132494,  1.53433014,  1.33181875],
       [ 1.71210111,  0.96081269,  1.02635646,  0.09554006]])

In [29]:
np.concatenate((A, B), axis = 0)

array([[-1.93181852, -0.24991737, -2.85593244, -0.48040933],
       [ 1.19563683, -0.56318729, -1.11334208, -0.21519366],
       [ 0.242841  , -0.95549184, -1.25239073,  0.4094317 ],
       [-1.28380913, -0.47069011, -1.59423148,  0.43463326],
       [-0.82246258,  1.48670351,  0.39458751, -1.07019225],
       [-0.780698  ,  0.98568704, -0.29036583,  1.20002403],
       [ 0.18748337,  1.01132494,  1.53433014,  1.33181875],
       [ 1.71210111,  0.96081269,  1.02635646,  0.09554006]])

In [30]:
################################################################################################################################